services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - client/.env

networks:
  app-network:
    driver: bridge